version: '3'
services:
  inventory:
    build:
      context: .
      dockerfile: dockerfile
    command: npm run start:app
    user: "node"
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
      - "8081:8081"
  price:
    image: adichallenge/adichallenge:product-engine