version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    command: node ./dist/index.js
    user: "node"
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"